<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - 01 - Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cea9a766-aeb0-4db3-8bca-3d3993e08eea</testSuiteGuid>
   <testCaseLink>
      <guid>a3584cff-b1b6-4119-a85c-d6e59094c8e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - Login Fail</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff32334e-497c-4ce4-b0d0-bca06db2d928</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ff32334e-497c-4ce4-b0d0-bca06db2d928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Condition</value>
         <variableId>e04e4ccf-9524-427f-8aba-ead66959a4f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff32334e-497c-4ce4-b0d0-bca06db2d928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UsernameFail</value>
         <variableId>93532f85-fdf3-4f8f-bc53-9159b7755422</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff32334e-497c-4ce4-b0d0-bca06db2d928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PasswordFail</value>
         <variableId>1dfae1df-8a7c-4980-8a17-69bb4424390b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff32334e-497c-4ce4-b0d0-bca06db2d928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UsernamePass</value>
         <variableId>48096a4c-e5a8-4fdc-943d-600fffcc93af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff32334e-497c-4ce4-b0d0-bca06db2d928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PasswordPass</value>
         <variableId>7e1051fc-235b-45e9-b628-51da3711fdb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c723a761-0f95-460b-8219-411868fac32d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5f0056c-c680-4d65-bd7f-d3ce31b426f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9515cc5-06b9-4776-a9ff-2f73e48908be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0946d27-b47f-4f45-a0a3-f4330dc52b1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4c3499-b41b-4f1b-9ff3-a1928c6edfe1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
